@startuml
hide footbox
skinparam roundcorner 20
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam note {
  FontName Impact
}


object Comment {
    String : comment
    String : author
    Talk : talk
    Date : createdOn
}

object Talk {
    String : title
    Person : speaker
    List<Conference> : conferences
}

object Person {
    String : name
    String : githubAccount
    String : blog
    List<Talk> : talks
}

object Conference {
    String : name
    String : city
    List<Talk> : talks
}

Conference }--{ Talk : has
Talk --{ Comment : has
Talk }--{ Person : hasSpeaker
@enduml